---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  "/api/v1/providers":
    get:
      summary: list providers
      tags:
      - Providers
      description: Retrieves a list of providers where their status is approved.
      security: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        type:
                          type: string
                        states:
                          type: array
                          items:
                            type: string
                        attributes:
                          type: object
                          properties:
                            name:
                              type: string
                            provider_type:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: integer
                                  name:
                                    type: string
                            locations:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: integer
                                  name:
                                    type: string
                                  address_1:
                                    type: string
                                  address_2:
                                    type: string
                                    nullable: true
                                  city:
                                    type: string
                                  state:
                                    type: string
                                  zip:
                                    type: string
                                  phone:
                                    type: string
                            website:
                              type: string
                            email:
                              type: string
                            cost:
                              type: string
                            insurance:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: integer
                                  name:
                                    type: string
                                  accepted:
                                    type: boolean
                            counties_served:
                              type: array
                              items:
                                type: object
                                properties:
                                  county_id:
                                    type: integer
                                  county_name:
                                    type: string
                            min_age:
                              type: number
                              nullable: true
                            max_age:
                              type: number
                              nullable: true
                            waitlist:
                              type: string
                              nullable: true
                            telehealth_services:
                              type: string
                              nullable: true
                            spanish_speakers:
                              type: string
                              nullable: true
                            at_home_services:
                              type: string
                              nullable: true
                            in_clinic_services:
                              type: string
                              nullable: true
                            logo:
                              type: string
                              nullable: true
                            updated_last:
                              type: string
                              format: date-time
                            status:
                              type: string
  "/api/v1/providers/{id}":
    get:
      summary: get provider by ID
      tags:
      - Providers
      description: Retrieves a single provider by their ID. Requires User login with
        authorization to access that providers info.
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        description: ID of the provider
        required: true
        schema:
          type: integer
      responses:
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        type:
                          type: string
                        states:
                          type: array
                          items:
                            type: string
                        attributes:
                          type: object
                          properties:
                            name:
                              type: string
                            provider_type:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: integer
                                  name:
                                    type: string
                            locations:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: integer
                                  name:
                                    type: string
                                  address_1:
                                    type: string
                                  address_2:
                                    type: string
                                    nullable: true
                                  city:
                                    type: string
                                  state:
                                    type: string
                                  zip:
                                    type: string
                                  phone:
                                    type: string
                            website:
                              type: string
                            email:
                              type: string
                            cost:
                              type: string
                            insurance:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: integer
                                  name:
                                    type: string
                                  accepted:
                                    type: boolean
                            counties_served:
                              type: array
                              items:
                                type: object
                                properties:
                                  county_id:
                                    type: integer
                                  county_name:
                                    type: string
                            min_age:
                              type: number
                              nullable: true
                            max_age:
                              type: number
                              nullable: true
                            waitlist:
                              type: string
                              nullable: true
                            telehealth_services:
                              type: string
                              nullable: true
                            spanish_speakers:
                              type: string
                              nullable: true
                            at_home_services:
                              type: string
                              nullable: true
                            in_clinic_services:
                              type: string
                              nullable: true
                            logo:
                              type: string
                              nullable: true
                            updated_last:
                              type: string
                              format: date-time
                            status:
                              type: string
  "/signup":
    post:
      summary: Registers a new user
      tags:
      - Users
      security: []
      parameters: []
      responses:
        '200':
          description: User successfully registered
          headers:
            Authorization:
              schema:
                type: string
                description: JWT Bearer token for user authorization
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      code:
                        type: integer
                        example: 200
                      message:
                        type: string
                        example: Signed up successfully.
                    required:
                    - code
                    - message
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      email:
                        type: string
                        format: email
                        example: user@example.com
                      created_at:
                        type: string
                        format: date-time
                      provider_id:
                        type: string
                        nullable: true
                        example: '61'
                      role:
                        type: string
                        enum:
                        - super_admin
                        - provider_admin
                        example: provider_admin
                      created_date:
                        type: string
                        example: 01/01/2025
                    required:
                    - id
                    - email
                    - created_at
                    - role
                required:
                - status
                - data
        '422':
          description: User registration failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      code:
                        type: integer
                        example: 422
                      message:
                        type: string
                        example: User couldn't be created successfully.
                    required:
                    - code
                    - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                      example: user@example.com
                    password:
                      type: string
                      format: password
                      example: password123
                      minLength: 6
                    password_confirmation:
                      type: string
                      format: password
                      example: password123
                      minLength: 6
                    provider_id:
                      type: string
                      example: '61'
                  required:
                  - email
                  - password
                  - password_confirmation
            examples:
              User registration example:
                summary: Example parameters for user registration request
                value:
                  user:
                    email: user@example.com
                    password: password123
                    password_confirmation: password123
                    provider_id: 61 (ID Will be currently set to nil by default at
                      this time)
        required: true
  "/login":
    post:
      summary: Logs in a user and returns a JWT token
      tags:
      - Users
      security: []
      parameters: []
      responses:
        '200':
          description: Login successful
          headers:
            Authorization:
              schema:
                type: string
              description: JWT token in Bearer format
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      code:
                        type: integer
                        example: 200
                      message:
                        type: string
                        example: Logged in successfully
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      email:
                        type: string
                        format: email
                        example: test@example.com
                      created_at:
                        type: string
                        format: date-time
                      provider_id:
                        type: integer
                        nullable: true
                        example: 61
                      role:
                        type: string
                        example: provider_admin
        '401':
          description: Invalid login credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      error:
                        type: string
                        example: Invalid Email or password.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: test@example.com
                    password:
                      type: string
                      example: password123
                  required:
                  - email
                  - password
            examples:
              User login example:
                summary: Example parameters for user login request
                value:
                  user:
                    email: test@example.com
                    password: password123
servers:
- url: https://uta-aba-finder-be-97eec9f967d0.herokuapp.com/
  description: Deployed Server
  variables:
    defaultHost:
      default: www.heroku.com
- url: http://localhost:3000
  description: Local Development Server
security:
- bearer_auth: []
