name: CI Testing

on:
  push:
    branches:
      - main  # or the branch you want to deploy from
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: utah_aba_finder_be_test
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'  # Specify your Ruby version here

      - name: Install Ruby gems
        run: bundle install

      - name: Wait for PostgreSQL
        run: sleep 10
        
      - name: Set up database
        run: |
          bin/rails db:create
          bin/rails db:migrate

      - name: Run RSpec tests
        run: bundle exec rspec